version: '3'
services:
  asku-api-server:
    image: asku-api-server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asku-api-server
    ports:
      - '8000:8000'
    env_file:
      - .env
    command: ['pm2-runtime', 'start', 'ecosystem.config.js']
